### ISSUE TITLE
An error occurred during the formation of the sql query

### ISSUE THREAD

**Issue by alexrm84** [line/kotlin-jdsl#676]
Hi!
I ran into a problem.
If you use 'in' when passing a collection, the request is not formed correctly.
The example is below.

```
fun delete(subIds: Collection<UUID>) {
    val query = jpql {
        deleteFrom(entity(AppInstanceDataSubscription::class))
            .where(path(AppInstanceDataSubscription::id).`in`(subIds))
    }
    val context = JpqlRenderContext()
    val render = JpqlRenderer()
    val rendered = render.render(query,context)
    entityManager.createQuery(rendered.query)
}
```
Result:
`org.hibernate.query.SyntaxException: At 1:77 and token '<EOF>', no viable alternative at input 'DELETE FROM AppInstanceDataSubscription AS AppInstanceDataSubscription WHERE *' [DELETE FROM AppInstanceDataSubscription AS AppInstanceDataSubscription WHERE ]`

Please check this behavior.

Spring Boot 3.2.3
Hibernate 6.4.4
Kotlin JDSL 3.3.1

**Comment by shouwn** [comment]
Could you please provide the definition of `AppInstanceDataSubscription Entity`? I think there might be an issue with the UUID.

It works fine when I test with the UUID locally, so if there are additional settings related to the UUID, I would like to see them provided as well.

Also, when I looked at the code, IN is not `Prepare Statement` friendly because it adds the elements that come in as parameters as params in the loop. I plan to fix this in 3.4.0.

**Comment by shouwn** [comment]
The Prepare Statement sent to JDBC was split into elements, even though I made the elements as a single param. 😢

**Comment by alexrm84** [comment]
There are no additional settings for the ID
![изображение](https://github.com/line/kotlin-jdsl/assets/40359224/ccb9f2db-c8ba-4949-ade9-1e3a0b5a7524)

**Comment by shouwn** [comment]
Is it possible to change the log level of `com.linecorp.kotlinjdsl` to debug to see the JPQL? If you change the level, you can see the following debug log:
![image](https://github.com/line/kotlin-jdsl/assets/31586979/287f2406-39c9-4233-b53e-43b9447706f1)

**Comment by shouwn** [comment]
If you use a UUID, it should look like this:
![image](https://github.com/line/kotlin-jdsl/assets/31586979/3379b556-355c-4d4b-baaa-ef1a83ebbd30)

**Comment by alexrm84** [comment]
I found the problem, it was between the chair and the monitor. 
I tested it on the project. I made a typo in the datasets, which returned an empty collection.
Thank you for your time.

**Comment by shouwn** [comment]
I'm glad to see that your issue has been resolved. I'll close this issue then.

**Comment by szanyierik** [comment]
This is a bug, and it is still present in DSL version 3.4.0.

Example code:

```kotlin
interface EmployeeRepository : JpaRepository<Employee, String>, KotlinJdslJpqlExecutor {
}
```

```kotlin
employeeRepository.findAll {
    select(entity(Employee::class))
        .from(entity(Employee::class))
        .where(path(Employee::id).`in`(ids))
}
```

When `ids` is a non-empty collection, the query is rendered correctly:
```
SELECT Employee FROM Employee AS Employee WHERE Employee.id IN (:param1){param1=asd}
```

However, when `ids` is an empty collection, the produced query is malformed (empty where clause):

```
SELECT Employee FROM Employee AS Employee WHERE {}
```

This is probably a result of [how `JpqlIn` is serialized](https://github.com/line/kotlin-jdsl/blob/471820cb84dcd3e2dd037a923c2cc0c52292220d/render/jpql/src/main/kotlin/com/linecorp/kotlinjdsl/render/jpql/serializer/impl/JpqlInSerializer.kt#L18) - when `compareValues` is empty, the serializer just returns without doing anything, resulting in a malformed query.

For reference, Hibernate deals with similar situations by replacing the predicate with `1=0`. For example,

```kotlin
@Query(
    """
        SELECT e FROM Employee AS e
        WHERE e.id IN :ids
    """
)
fun findAllEmployeesById(ids: Collection<String>): List<Employee>
```

turns into

```
select
    e1_0.id,
    e1_0.name
from
    employee e1_0 
where
    1=0
```

when `ids` is an empty collection.

**Comment by shouwn** [comment]
@szanyierik 

You're right. I didn't think of this because I was writing the in condition to be enabled only if not empty when passing the collection parameter each time.

Maybe you could open a new issue for this? 

This should be deployed as a hotfix. 

I'll work on it this Saturday and release it.
